source 'https://cdn.cocoapods.org'
#source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'TGASDK-Swift' do
  pod 'TGAIOSSDK', :path => '../'
  pod 'Google-Mobile-Ads-SDK'
  #pod 'CocoaDebug', '~> 1.7.2'
  pod 'AppLovinMediationAdColonyAdapter', '~> 4.9.0.0.2'
  #pod 'AppLovinMediationUnityAdsAdapter'
  pod 'AppLovinMediationVungleAdapter', '~> 6.12.0.2'

  # 第三方SDK
  #pod 'CocoaDebug', '~> 1.7.2'
  pod 'XBPickerView', '~> 2.1.0' #选择器
  pod 'XBDialog', '~> 1.6.0'
end

target 'TGASDK-OC' do
  pod 'TGAIOSSDK', :path => '../'
  pod 'AppLovinMediationAdColonyAdapter', '~> 4.9.0.0.2'
  #pod 'AppLovinMediationUnityAdsAdapter'
  pod 'AppLovinMediationVungleAdapter', '~> 6.12.0.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
